version: "3.3"

services:
  e-threader:
    build: ./app
    volumes:
      - ./app:/app
      - ./db.sqlite:/db.sqlite
      - ./config.yaml:/config.yaml
    env_file:
      - .env
    restart: always
    tty: true
