FROM python:3-slim

ADD requirements.txt /requirements.txt

RUN apt-get update && apt-get upgrade -y \
    # apt-get install -y --no-install-recommends \
    && pip install -r /requirements.txt

CMD ["python", "/app/main.py"]
