FROM python:3-slim

ADD requirements.txt /opt/requirements.txt

RUN apt-get update && apt-get upgrade -y \
    # apt-get install -y --no-install-recommends \
    && pip install -r /opt/requirements.txt

CMD ["sh"]
# CMD ["python", "/opt/app/main.py"]
